name: Daily Horoscope Update
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Updated to v4 to clear the Node.js warning
      - uses: actions/checkout@v4 
      
      # Added step to install dependencies
      - name: Install Dependencies
        run: pip install requests beautifulsoup4
        
      - name: Run Scraper
        run: python scraper.py
        
      - name: Commit and Push
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@example.com'
          git commit -am "Update Horoscope" || echo "No changes to commit"
          git push
